language: node_js
node_js:
  - 13.6.0
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache

stages:
  - compile
  - check
  - deploy

env:
  - CI=false

jobs:
  include:
    - stage: compile
      script:
        - npm install
        - npm start -- --silent &
    - stage: check
      script: $(npm bin)/cypress run

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir ./build
  skip_cleanup: true
  on:
    branch: master
